- name: mysql-server setup
  hosts: mysql
  become: yes
  vars:
    mysql_login_password: Amar@123
    host: mysql
  tasks:
  - name: installing my sql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: start my sql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: connect mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_login_password}}"
      login_host: "{{ host }}"
    ignore_errors: True
    register: mysql_info

  - name: print the mysql info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"